DROP SEQUENCE IF EXISTS ROLL_NUMBER_TABLE_SEQ;
DROP TABLE IF EXISTS HFW_STUDENT_TABLE;
DROP TABLE IF EXISTS HFW_ID_GENERATOR;

CREATE SEQUENCE ROLL_NUMBER_TABLE_SEQ;
--ALTER SEQUENCE ROLL_NUMBER_TABLE_SEQ RESTART WITH 1000;

CREATE TABLE HFW_ID_GENERATOR(
	SEQUENCE_NAME VARCHAR,
	NEXT_VAL BIGINT
); 
INSERT INTO HFW_ID_GENERATOR VALUES('ROLL_NUMBER_TABLE_SEQ', 1001);

CREATE TABLE HFW_STUDENT_TABLE
	(ROLL_NUMBER			BIGINT PRIMARY KEY,
	 NAME 					VARCHAR(50) NOT NULL,
	 EMAIL					VARCHAR(50),
	 MOBILE					VARCHAR(10),
	 ADDRESS				VARCHAR(200)
);	 