CREATE TABLE JM3005_ONETOMANY_UNI_COURSE 
  ( 
     ID      BIGINT AUTO_INCREMENT, 
     TITLE   VARCHAR(50), 
     
     PRIMARY KEY(ID),
     UNIQUE KEY TITLE_UNIQUE_KEY (TITLE)
  );
  
  CREATE TABLE JM3005_ONETOMANY_UNI_ASSIGNMENT 
  ( 
     ID      BIGINT AUTO_INCREMENT, 
     DESCRIPTION   VARCHAR(200),
     COURSE_ID 		BIGINT,
     
     PRIMARY KEY(ID),
     FOREIGN KEY(COURSE_ID) REFERENCES JM3005_ONETOMANY_UNI_COURSE(ID)
  );