DROP TABLE IF EXISTS JM3005_MANYTOMANY_BI_Person;
DROP TABLE IF EXISTS JM3005_MANYTOMANY_BI_ADDRESS;
DROP TABLE IF EXISTS JM3005_MANYTOMANY_BI_PERSON_JM3005_MANYTOMANY_BI_ADDRESS;

CREATE TABLE JM3005_MANYTOMANY_BI_ADDRESS (
    id BIGINT AUTO_INCREMENT,
    number VARCHAR(255) ,
    street VARCHAR(255) ,
    PRIMARY KEY ( id )
);

CREATE TABLE JM3005_MANYTOMANY_BI_Person (
    id BIGINT  AUTO_INCREMENT,
    name varchar,
    PRIMARY KEY ( id )
);

CREATE TABLE JM3005_MANYTOMANY_BI_Person_JM3005_MANYTOMANY_BI_ADDRESS (
    Owners_id BIGINT NOT NULL ,
    addresses_id BIGINT NOT NULL
);

ALTER TABLE JM3005_MANYTOMANY_BI_Person_JM3005_MANYTOMANY_BI_ADDRESS
ADD CONSTRAINT BI_addresses_id_fk
FOREIGN KEY (addresses_id) REFERENCES JM3005_MANYTOMANY_BI_ADDRESS;

ALTER TABLE JM3005_MANYTOMANY_BI_Person_JM3005_MANYTOMANY_BI_ADDRESS
ADD CONSTRAINT BI_Owners_id_fk
FOREIGN KEY (Owners_id) REFERENCES JM3005_MANYTOMANY_BI_Person;