CREATE TABLE JM3005_ONETOMANY_BI_COURSE 
  ( 
     ID      BIGINT AUTO_INCREMENT, 
     TITLE   VARCHAR(50), 
     
     PRIMARY KEY(ID),
  );
  
  CREATE TABLE JM3005_ONETOMANY_BI_ASSIGNMENT 
  ( 
     ID      BIGINT AUTO_INCREMENT, 
     DESCRIPTION   VARCHAR(200),
     COURSE_ID 		BIGINT,
     
     PRIMARY KEY(ID),
     FOREIGN KEY(COURSE_ID) REFERENCES JM3005_ONETOMANY_BI_COURSE(ID)
  );