-- AUTO
CREATE TABLE JM3005_STUDENT_AUTO(
ROLL_NO BIGINT PRIMARY KEY,
NAME VARCHAR(50),
AGE NUMBER,
PERCENTAGE DECIMAL 
)

CREATE SEQUENCE HIBERNATE_SEQUENCE;
ALTER SEQUENCE HIBERNATE_SEQUENCE RESTART WITH 10001;
DROP TABLE STUDENT;

-- IDENTITY
CREATE TABLE JM3005_STUDENT_IDENTITY(
ROLL_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
AGE NUMBER,
PERCENTAGE DECIMAL 
)

-- SEQUENCE
CREATE SEQUENCE SEQ_JM3005_STUDENT_SEQUENCE;
CREATE TABLE JM3005_STUDENT_SEQUENCE(
ROLL_NO BIGINT PRIMARY KEY,
NAME VARCHAR(50),
AGE NUMBER,
PERCENTAGE DECIMAL 
)