CREATE TABLE JM3005_STUDENT_AUTO(
ROLL_NO BIGINT PRIMARY KEY,
NAME VARCHAR(50),
AGE NUMBER,
PERCENTAGE DECIMAL 
)

CREATE SEQUENCE HIBERNATE_SEQUENCE;
ALTER SEQUENCE HIBERNATE_SEQUENCE RESTART WITH 10001;
DROP TABLE STUDENT;